spring:
  
  config:
    import: optional:file:.env

  application:
    name: market    

  datasource:
    url: ${DEFAULT_DB_URL}
    username: ${DEFAULT_DB_USERNAME}
    password: ${DEFAULT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    
file:
  directory: ${DEFAULT_FILE_DIRECTORY}
